/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package accesscontrolsystem;

import static accesscontrolsystem.OpenFileForm.fileName;
import java.awt.Color;
import java.awt.GridLayout;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Avadh
 */
public class EmployeeMenu extends javax.swing.JFrame {
    
    
    /**
     * Creates new form Menu
     */
    public EmployeeMenu() throws SQLException {
        initComponents();
        init();
        createFileList(fileList);
        
        
        currentUser.setText("User: " + LoginCurrent.username);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        currentUser = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        policyButton = new javax.swing.JButton();
        logButton = new javax.swing.JButton();
        browseButton = new javax.swing.JButton();
        tabbedPanel = new javax.swing.JTabbedPane();
        welcomeTab = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        browseTab = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        fileList = new javax.swing.JList<>();
        addFileButton = new javax.swing.JButton();
        openFileButton = new javax.swing.JButton();
        removeFileButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        policyTab = new javax.swing.JPanel();
        logTab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        logText = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuPanel.setBackground(new java.awt.Color(124, 124, 124));

        currentUser.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        currentUser.setForeground(new java.awt.Color(240, 240, 240));
        currentUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currentUser.setText("jLabel1");

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        policyButton.setText("Policies");
        policyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                policyButtonActionPerformed(evt);
            }
        });

        logButton.setText("Log");
        logButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logButtonActionPerformed(evt);
            }
        });

        browseButton.setText("Browse");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(currentUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(policyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(browseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(browseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(policyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(currentUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logoutButton)
                .addGap(21, 21, 21))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Welcome");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Use the buttons on the left panel to navigate through the system");

        javax.swing.GroupLayout welcomeTabLayout = new javax.swing.GroupLayout(welcomeTab);
        welcomeTab.setLayout(welcomeTabLayout);
        welcomeTabLayout.setHorizontalGroup(
            welcomeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomeTabLayout.createSequentialGroup()
                .addGroup(welcomeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(welcomeTabLayout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(jLabel1))
                    .addGroup(welcomeTabLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel2)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        welcomeTabLayout.setVerticalGroup(
            welcomeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomeTabLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addContainerGap(264, Short.MAX_VALUE))
        );

        tabbedPanel.addTab("Welcome", welcomeTab);

        fileList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(fileList);

        addFileButton.setText("Add File...");
        addFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFileButtonActionPerformed(evt);
            }
        });

        openFileButton.setText("Open File");
        openFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileButtonActionPerformed(evt);
            }
        });

        removeFileButton.setText("Remove");
        removeFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeFileButtonActionPerformed(evt);
            }
        });

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout browseTabLayout = new javax.swing.GroupLayout(browseTab);
        browseTab.setLayout(browseTabLayout);
        browseTabLayout.setHorizontalGroup(
            browseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(browseTabLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(browseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(browseTabLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(browseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removeFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(openFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, browseTabLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167))))
        );
        browseTabLayout.setVerticalGroup(
            browseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(browseTabLayout.createSequentialGroup()
                .addGroup(browseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(browseTabLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(removeFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(browseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(openFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(browseTabLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        tabbedPanel.addTab("Browse", browseTab);

        javax.swing.GroupLayout policyTabLayout = new javax.swing.GroupLayout(policyTab);
        policyTab.setLayout(policyTabLayout);
        policyTabLayout.setHorizontalGroup(
            policyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 781, Short.MAX_VALUE)
        );
        policyTabLayout.setVerticalGroup(
            policyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );

        tabbedPanel.addTab("Policies", policyTab);

        logText.setColumns(20);
        logText.setRows(5);
        jScrollPane1.setViewportView(logText);

        jButton1.setText("Today");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Past Week");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("All");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout logTabLayout = new javax.swing.GroupLayout(logTab);
        logTab.setLayout(logTabLayout);
        logTabLayout.setHorizontalGroup(
            logTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logTabLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(logTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(logTabLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        logTabLayout.setVerticalGroup(
            logTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logTabLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(logTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        tabbedPanel.addTab("Log", logTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabbedPanel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabbedPanel)
        );

        tabbedPanel.getAccessibleContext().setAccessibleName("polic");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void init() throws SQLException {
        logText.setText(null);
        ArrayList<String> log = null;
        try {
            log = logData(3);
        } catch (SQLException ex) {
            Logger.getLogger(EmployeeMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        for (String a : log) {
            logText.append(a + "\n");
        }
    }
    
    public void createFileList(JList<String> list) {
        AccessControlSystem program = new AccessControlSystem();
        DefaultListModel<String> model = new DefaultListModel<>();
        ArrayList<String> names = new ArrayList<>();
        
        try {
            Connection conn = program.DBConnect();
            String query = "SELECT FileName, Role from resource";
            
            PreparedStatement stmt = conn.prepareStatement(query);
            ResultSet result = stmt.executeQuery();
            
            while (result.next()) {
                String name = result.getString("FileName");
                String role = result.getString("Role");
                
                names.add(name + "                                      " + role);
                
            }
        }
        catch (SQLException e){
            System.err.println("File List Error:" + e.getMessage());
        }
        
        for (String a : names) {
            model.addElement(a);
        }
        
        fileList.setModel(model);
    }
    
    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        
        LoginForm login = new LoginForm();
        Logout.logOut(this, login);
        Logout.updateLog(LoginCurrent.username, LoginCurrent.userType);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void logButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logButtonActionPerformed
        // TODO add your handling code here:
        
        tabbedPanel.setSelectedIndex(3);
        logText.setText(null);
        ArrayList<String> log = null;
        try {
            log = logData(3);
        } catch (SQLException ex) {
            Logger.getLogger(EmployeeMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        for (String a : log) {
            logText.append(a + "\n");
        }
        
    }//GEN-LAST:event_logButtonActionPerformed

    private void policyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_policyButtonActionPerformed
        // TODO add your handling code here:
        tabbedPanel.setSelectedIndex(2);
        GraphDraw draw = new GraphDraw();
        String currentUser = LoginCurrent.username;
        String userRole = "";
        ArrayList<String> files = new ArrayList<>();
        
        
        AccessControlSystem program = new AccessControlSystem();
        try {
            Connection conn = program.DBConnect();
            String query = "SELECT Role From login WHERE "
                    + "Username = '" + currentUser + "'";
            PreparedStatement stmt = conn.prepareStatement(query);
            ResultSet result = stmt.executeQuery();
            
            while (result.next()) {
                userRole = result.getString("Role");
            }
        }
        catch (SQLException e) {
            System.out.println("Error: " + e);
        }
        
        try {
            Connection conn = program.DBConnect();
            String query = "SELECT fileName From resource WHERE "
                    + "Role = '" + userRole + "'";
            PreparedStatement stmt = conn.prepareStatement(query);
            ResultSet result = stmt.executeQuery();
            
            while (result.next()) {
                files.add(result.getString("fileName"));
            }
        }
        catch (SQLException e) {
            System.out.println("Error: " + e);
        }
        
        Node user = new Node();
        user.setDisplayName(currentUser);
        user.setColor(Color.BLACK);
        user.setPosition(new Node.Position(100, 100));
        draw.addNode(user);
        
        Node category = new Node();
        category.setDisplayName(userRole);
        category.setColor(Color.GREEN);
        category.setPosition(new Node.Position(200, 100));
        draw.addNode(category);
        
        Edge e1 = new Edge(user, category);
        e1.setFocussed(true);
        e1.setColor(Color.BLACK);
        draw.addEdge(e1);
        
        Node action = new Node();
        action.setDisplayName("Read");
        action.setColor(Color.BLUE);
        action.setPosition(new Node.Position(300, 100));
        draw.addNode(action);
        
        Edge e2 = new Edge(category, action);
        e2.setFocussed(true);
        e2.setColor(Color.BLACK);
        draw.addEdge(e2);
        
        int pos = 0;
        
        for (int i = 0; i < files.size(); i++) {
            String fileName = files.get(i);
            
            Node file = new Node();
            file.setDisplayName(fileName);
            file.setColor(Color.BLUE);
            file.setPosition(new Node.Position(400, pos));
            draw.addNode(file);
            
            Edge e3 = new Edge(action, file);
            e3.setFocussed(true);
            e3.setColor(Color.BLACK);
            draw.addEdge(e3);
            
            pos = pos + 150;
        }
        
        draw.setSize(800, 800);
        draw.setVisible(true);
        policyTab.add(draw);
        policyTab.setSize(800, 800);
        policyTab.setVisible(true);
    }//GEN-LAST:event_policyButtonActionPerformed

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        // TODO add your handling code here:
        
        tabbedPanel.setSelectedIndex(1);
    }//GEN-LAST:event_browseButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        logText.setText(null);
        ArrayList<String> log = null;
        try {
            log = logData(1);
        } catch (SQLException ex) {
            Logger.getLogger(EmployeeMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        for (String a : log) {
            logText.append(a + "\n");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        logText.setText(null);
        ArrayList<String> log = null;
        try {
            log = logData(2);
        } catch (SQLException ex) {
            Logger.getLogger(EmployeeMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        for (String a : log) {
            logText.append(a + "\n");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        logText.setText(null);
        ArrayList<String> log = null;
        try {
            log = logData(2);
        } catch (SQLException ex) {
            Logger.getLogger(EmployeeMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        for (String a : log) {
            logText.append(a + "\n");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void addFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFileButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        int val = chooser.showOpenDialog(this);
        
        if (val == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            String dir = System.getProperty("user.dir");
            String fileName = file.getName();
            String type = "";
            int index = fileName.lastIndexOf(".");
            
            if (index > 0) {
                type = fileName.substring(index + 1);
            }
            
            System.out.println(type);
            if (type.equals("txt")) {
                System.out.println("success");
                try {
                    FileManager manager = new FileManager();
                    
                    manager.addFile(this, file, fileName, dir);
                    new FileRole(fileName).setVisible(true);
                    updateLogAdd(LoginCurrent.username, LoginCurrent.userType, fileName);
                }
                catch (Exception e){
                    System.out.println("File access failed: " + e);
                }
            }
            else {
                JOptionPane.showMessageDialog(this, "Invalid File Type: Please "
                        + "choose select a text file");
            }
        }
        else {
            System.out.println("No file chosen");
        }

    }//GEN-LAST:event_addFileButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        createFileList(fileList);
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void openFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileButtonActionPerformed
        // TODO add your handling code here:
        
        AccessControlSystem program  = new AccessControlSystem();
        
        String userRole = "";
        String selectedRole = "";
        String fileName = "";
        
        if (!fileList.isSelectionEmpty()) {
                FileManager manager = new FileManager();
                DefaultListModel m = (DefaultListModel) fileList.getModel();
                String value = fileList.getSelectedValue();
                
                if (value.contains("      ")) {
                    selectedRole = value.substring(value.lastIndexOf(" ") + 1);
                    selectedRole = selectedRole.replaceAll("\\s+","");
                    fileName = value.substring(0, value.indexOf("      "));
                }
                
                
        }
        else {
            JOptionPane.showMessageDialog(this, "File Not Chosen: Please ensure "
                    + "that a file has been selected");
        }
        
        try {
            Connection conn = program.DBConnect();
            
            String getRole = "SELECT Role FROM login WHERE Username = "
                    + "'" + LoginCurrent.username + "'";
            PreparedStatement stmt = conn.prepareStatement(getRole);
            ResultSet result = stmt.executeQuery();
            
            while (result.next()) {
                userRole = result.getString("Role");
            }
            
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
        
        
        if ((userRole.compareTo(selectedRole) == 0)) {
            openFile(fileName);
            updateLogOpen(LoginCurrent.username, LoginCurrent.userType, fileName);
        }
        else {
            JOptionPane.showMessageDialog(this, "No Access: This account does "
                    + "not have access to this resource");
        }
    }//GEN-LAST:event_openFileButtonActionPerformed

    private void removeFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeFileButtonActionPerformed
        // TODO add your handling code here:

        AccessControlSystem program  = new AccessControlSystem();

        if (!fileList.isSelectionEmpty()) {
            try {
                FileManager manager = new FileManager();
                DefaultListModel m = (DefaultListModel) fileList.getModel();
                String value = fileList.getSelectedValue();
                System.out.println(value);

                if (value.contains("      ")) {
                    value = value.substring(0, value.indexOf("      "));
                }

                System.out.println(value);

                Connection conn = program.DBConnect();
                String query = "DELETE FROM resource WHERE "
                + "FileName = '" + value + "'";

                PreparedStatement stmt = conn.prepareStatement(query);
                stmt.execute();
                stmt.close();

                m.remove(fileList.getSelectedIndex());

                manager.removeFile(value);
            }
            catch (SQLException e){
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "File Not Chosen: Please ensure "
                + "that a file has been selected");
        }

    }//GEN-LAST:event_removeFileButtonActionPerformed
    
    private void openFile(String fileName) {
        String directory = System.getProperty("user.dir");
        directory = directory + "\\files\\" + fileName;
        System.out.println(directory);
        
        String execute = "rundll32 url.dll,FileProtocolHandler ";
        
        File file = new File(directory);
        
        try {
            if(file.exists()) {
                file.setReadOnly();
                Process process = Runtime.getRuntime().exec(execute + directory);
                process.waitFor();
            }
            else {
                
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e);
        }
    }
    
    public static void updateLogAdd(String username, String type, String file) {
        AccessControlSystem program = new AccessControlSystem();
        try {
            Connection conn = program.DBConnect();
            
            //Get current date and time, ie the date and time of login
            java.util.Date date = new java.util.Date();
            java.sql.Date SQLDate = new  java.sql.Date(date.getTime());
            Timestamp SQLTime = new Timestamp(date.getTime());
            
            String entry = "[" + type + "]" + " user " + username + " has added file " + file + ".";
            
            String query = "INSERT INTO log(DateOfEntry, TimeOfEntry, Entry) "
                    + "VALUES(?, ?, '"+ entry +"')";
            
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setDate(1, SQLDate);
            stmt.setTimestamp(2, SQLTime);
            stmt.executeUpdate();
            stmt.close();
            
        }
        catch (SQLException e){
            System.err.println(e);
        }
    }
    
    public static void updateLogOpen(String username, String type, String file) {
        AccessControlSystem program = new AccessControlSystem();
        try {
            Connection conn = program.DBConnect();
            
            //Get current date and time, ie the date and time of login
            java.util.Date date = new java.util.Date();
            java.sql.Date SQLDate = new  java.sql.Date(date.getTime());
            Timestamp SQLTime = new Timestamp(date.getTime());
            
            String entry = "[" + type + "]" + " user " + username + " has accessed file " + file + ".";
            
            String query = "INSERT INTO log(DateOfEntry, TimeOfEntry, Entry) "
                    + "VALUES(?, ?, '"+ entry +"')";
            
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setDate(1, SQLDate);
            stmt.setTimestamp(2, SQLTime);
            stmt.executeUpdate();
            stmt.close();
            
        }
        catch (SQLException e){
            System.err.println(e);
        }
    }
    
    private ArrayList logData(int date) throws SQLException {
        AccessControlSystem system = new AccessControlSystem();
        ArrayList<String> log = new ArrayList<String>();
        
        String query = "";
        
        if (date == 1)  {
            query = "SELECT DateOfEntry, TimeOfEntry, Entry FROM log WHERE "
                    + "DateOfEntry = curdate()";
        }
        else if (date == 2) {
            query = "SELECT DateOfEntry, TimeOfEntry, Entry FROM log WHERE "
                    + "DateOfEntry > date_sub(now(), interval 1 week)";
        }
        else if (date == 3) {
            query = "SELECT DateOfEntry, TimeOfEntry, Entry FROM log";
        }
        
        ResultSet result = system.getLog(query);
        
        while (result.next()) {
            String entryDate = result.getString("DateOfEntry");
            String entryTime = result.getString("TImeOFEntry");
            String entry = result.getString("Entry");
            
            String logText = "" + entryDate + " " + entryTime + "   " + entry;
            
            log.add(logText); 
        }
        
        return log;
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new EmployeeMenu().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(EmployeeMenu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFileButton;
    private javax.swing.JButton browseButton;
    private javax.swing.JPanel browseTab;
    private javax.swing.JLabel currentUser;
    private javax.swing.JList<String> fileList;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logButton;
    private javax.swing.JPanel logTab;
    private javax.swing.JTextArea logText;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton openFileButton;
    private javax.swing.JButton policyButton;
    private javax.swing.JPanel policyTab;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton removeFileButton;
    private javax.swing.JTabbedPane tabbedPanel;
    private javax.swing.JPanel welcomeTab;
    // End of variables declaration//GEN-END:variables
}
